import AppKit
import ImageIO
import UniformTypeIdentifiers
import Darwin

public enum BridgeError: LocalizedError {
    case invalidImage, clipboardWriteFailed, imageTooLarge, unsafeSaveDirectory
    public var errorDescription: String? {
        switch self {
        case .invalidImage: "The image could not be read or converted to PNG."
        case .clipboardWriteFailed: "macOS could not update the clipboard."
        case .imageTooLarge: "The image exceeds the 100 MiB or 40 megapixel safety limit."
        case .unsafeSaveDirectory: "The image folder must be a directory owned by you, not a symbolic link."
        }
    }
}

public enum PathText {
    public static func representation(of url: URL, quoteForTerminal: Bool) -> String {
        let path = url.path
        guard quoteForTerminal else { return path }
        let safe = CharacterSet(charactersIn: "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789/._-~")
        guard path.unicodeScalars.contains(where: { !safe.contains($0) }) else { return path }
        return "'" + path.replacingOccurrences(of: "'", with: "'\\''") + "'"
    }
}

public struct ImagePayload {
    public static let maximumEncodedBytes = 100 * 1024 * 1024
    public static let maximumPixels = 40_000_000
    public let png: Data
    public let tiff: Data?

    public init(data: Data) throws {
        guard data.count <= Self.maximumEncodedBytes else { throw BridgeError.imageTooLarge }
        guard let source = CGImageSourceCreateWithData(data as CFData, nil),
              let properties = CGImageSourceCopyPropertiesAtIndex(source, 0, nil) as? [CFString: Any],
              let width = properties[kCGImagePropertyPixelWidth] as? NSNumber,
              let height = properties[kCGImagePropertyPixelHeight] as? NSNumber else { throw BridgeError.invalidImage }
        try Self.validateDimensions(width: width.intValue, height: height.intValue)
        guard let image = CGImageSourceCreateImageAtIndex(source, 0, nil) else { throw BridgeError.invalidImage }
        if CGImageSourceGetType(source) as String? == UTType.png.identifier {
            png = data
        } else {
            let buffer = NSMutableData()
            guard let destination = CGImageDestinationCreateWithData(buffer, UTType.png.identifier as CFString, 1, nil) else {
                throw BridgeError.invalidImage
            }
            CGImageDestinationAddImage(destination, image, nil)
            guard CGImageDestinationFinalize(destination) else { throw BridgeError.invalidImage }
            png = buffer as Data
        }
        // PNG covers modern receivers; TIFF keeps compatibility with AppKit image fields.
        tiff = NSBitmapImageRep(cgImage: image).representation(using: .tiff, properties: [:])
    }

    static func validateDimensions(width: Int, height: Int) throws {
        guard width > 0, height > 0 else { throw BridgeError.invalidImage }
        guard width <= maximumPixels, height <= maximumPixels,
              width <= maximumPixels / height else { throw BridgeError.imageTooLarge }
    }
}

@MainActor
public final class ClipboardBridge {
    public static let marker = NSPasteboard.PasteboardType("local.screenshotbridge.processed")
    private static let ignoredTypes = ["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType"]
    public let pasteboard: NSPasteboard
    public var saveDirectory: URL
    public var quoteForTerminal = true
    public private(set) var observedChangeCount: Int
    public private(set) var lastFile: URL?

    public init(pasteboard: NSPasteboard, saveDirectory: URL) {
        self.pasteboard = pasteboard
        self.saveDirectory = saveDirectory
        observedChangeCount = pasteboard.changeCount
    }

    public func skipCurrentClipboard() { observedChangeCount = pasteboard.changeCount }

    /// Only new, single, image-only clipboard items are materialized. No startup replay.
    @discardableResult
    public func processClipboardIfChanged() throws -> URL? {
        let revision = pasteboard.changeCount
        guard revision != observedChangeCount else { return nil }
        observedChangeCount = revision
        let types = pasteboard.types ?? []
        guard !types.contains(Self.marker),
              !Self.ignoredTypes.contains(where: { types.contains(.init($0)) }),
              !types.contains(.fileURL), !types.contains(.URL), !types.contains(.string),
              let items = pasteboard.pasteboardItems, items.count == 1,
              let original = items.first else { return nil }
        let imageTypes = original.types.filter { UTType($0.rawValue)?.conforms(to: .image) == true }
        guard let selectedType = ([NSPasteboard.PasteboardType.png, .tiff] + imageTypes)
            .first(where: { original.types.contains($0) }),
              let data = original.data(forType: selectedType) else { return nil }
        let payload = try ImagePayload(data: data)
        // Publish validated raster formats instead of retaining arbitrary app-specific payloads.
        try PrivateImageStore.prepareDirectory(saveDirectory)
        let formatter = DateFormatter()
        formatter.locale = Locale(identifier: "en_US_POSIX")
        formatter.dateFormat = "yyyy-MM-dd_HH-mm-ss-SSS"
        let file = saveDirectory.appendingPathComponent("Screenshot-\(formatter.string(from: Date()))-\(UUID().uuidString.prefix(8)).png")
        try PrivateImageStore.write(payload.png, to: file)
        guard pasteboard.changeCount == revision else {
            // This file was never exposed on the clipboard, so it is safe to remove.
            try? FileManager.default.removeItem(at: file)
            return nil
        }
        try publish(file: file, payload: payload)
        return file
    }

    /// expectedChangeCount prevents a delayed saved screenshot from replacing newer copied text.
    @discardableResult
    public func processSavedScreenshot(_ file: URL, expectedChangeCount: Int) throws -> Bool {
        guard pasteboard.changeCount == expectedChangeCount else { return false }
        let values = try file.resourceValues(forKeys: [.isRegularFileKey, .isSymbolicLinkKey, .fileSizeKey])
        guard values.isRegularFile == true, values.isSymbolicLink != true else { throw BridgeError.invalidImage }
        guard let size = values.fileSize, size <= ImagePayload.maximumEncodedBytes else { throw BridgeError.imageTooLarge }
        let payload = try ImagePayload(data: Data(contentsOf: file, options: .mappedIfSafe))
        var clipboardFile = file
        if !["png", "jpg", "jpeg", "webp"].contains(file.pathExtension.lowercased()) {
            try PrivateImageStore.prepareDirectory(saveDirectory)
            clipboardFile = saveDirectory.appendingPathComponent("Screenshot-\(UUID().uuidString).png")
            try PrivateImageStore.write(payload.png, to: clipboardFile)
        }
        guard pasteboard.changeCount == expectedChangeCount else {
            if clipboardFile != file { try? FileManager.default.removeItem(at: clipboardFile) }
            return false
        }
        try publish(file: clipboardFile, payload: payload)
        return true
    }

    public func copyLastPathOnly() throws {
        guard let lastFile else { return }
        pasteboard.clearContents()
        guard pasteboard.setString(PathText.representation(of: lastFile, quoteForTerminal: quoteForTerminal), forType: .string) else {
            throw BridgeError.clipboardWriteFailed
        }
        observedChangeCount = pasteboard.changeCount
    }

    private func publish(file: URL, payload: ImagePayload) throws {
        let item = NSPasteboardItem()
        item.setData(payload.png, forType: .png)
        if let tiff = payload.tiff { item.setData(tiff, forType: .tiff) }
        item.setString(file.absoluteString, forType: .fileURL)
        item.setString(PathText.representation(of: file, quoteForTerminal: quoteForTerminal), forType: .string)
        item.setString("1", forType: Self.marker)
        pasteboard.clearContents()
        guard pasteboard.writeObjects([item]) else { throw BridgeError.clipboardWriteFailed }
        observedChangeCount = pasteboard.changeCount
        lastFile = file
    }
}
