import AppKit
import Darwin
import Testing
@testable import BridgeCore

@MainActor
private func fixture() throws -> Data {
    let bitmap = try #require(NSBitmapImageRep(bitmapDataPlanes: nil, pixelsWide: 8, pixelsHigh: 6,
        bitsPerSample: 8, samplesPerPixel: 4, hasAlpha: true, isPlanar: false,
        colorSpaceName: .deviceRGB, bytesPerRow: 0, bitsPerPixel: 0))
    let blue = NSColor(deviceRed: 0.15, green: 0.45, blue: 0.9, alpha: 1)
    for x in 0..<8 { for y in 0..<6 { bitmap.setColor(blue, atX: x, y: y) } }
    return try #require(bitmap.representation(using: .png, properties: [:]))
}

@MainActor
private func withBridge(_ body: (ClipboardBridge, URL) throws -> Void) throws {
    let folder = FileManager.default.temporaryDirectory.resolvingSymlinksInPath().appendingPathComponent("BridgeTests-\(UUID())")
    try FileManager.default.createDirectory(at: folder, withIntermediateDirectories: true)
    let pasteboard = NSPasteboard.withUniqueName()
    let bridge = ClipboardBridge(pasteboard: pasteboard, saveDirectory: folder)
    defer { pasteboard.releaseGlobally(); try? FileManager.default.removeItem(at: folder) }
    try body(bridge, folder)
}

@MainActor
private func copyImage(_ data: Data, to pasteboard: NSPasteboard, extraType: NSPasteboard.PasteboardType? = nil) {
    let item = NSPasteboardItem()
    item.setData(data, forType: .png)
    if let extraType { item.setString("existing", forType: extraType) }
    pasteboard.clearContents()
    pasteboard.writeObjects([item])
}

@Test @MainActor
func clipboardImageBecomesRealFileAndThreeReadableRepresentations() throws {
    try withBridge { bridge, _ in
        let png = try fixture()
        copyImage(png, to: bridge.pasteboard)
        let file = try #require(try bridge.processClipboardIfChanged())
        #expect(try Data(contentsOf: file) == png)
        #expect(bridge.pasteboard.data(forType: .png) == png)
        #expect(bridge.pasteboard.string(forType: .string) == file.path)
        #expect(bridge.pasteboard.string(forType: .fileURL) == file.absoluteString)
        let image = try #require(NSImage(pasteboard: bridge.pasteboard))
        #expect(image.size.width == 8 && image.size.height == 6)
        let urls = try #require(bridge.pasteboard.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]))
        #expect((urls.first as? URL) == file)
        #expect(bridge.pasteboard.pasteboardItems?.count == 1)
    }
}

@Test @MainActor
func selfPublicationDoesNotLoopOrDuplicateFiles() throws {
    try withBridge { bridge, folder in
        copyImage(try fixture(), to: bridge.pasteboard)
        _ = try bridge.processClipboardIfChanged()
        #expect(try bridge.processClipboardIfChanged() == nil)
        #expect(try FileManager.default.contentsOfDirectory(atPath: folder.path).count == 1)
        // Even a clipboard manager replaying our formats is skipped using the marker.
        copyImage(try fixture(), to: bridge.pasteboard, extraType: ClipboardBridge.marker)
        #expect(try bridge.processClipboardIfChanged() == nil)
    }
}

@Test(arguments: [NSPasteboard.PasteboardType.string, .fileURL, .URL,
    .init("org.nspasteboard.ConcealedType"), .init("org.nspasteboard.TransientType"), .init("org.nspasteboard.AutoGeneratedType")])
@MainActor
func existingTextFilesAndPrivateItemsArePreserved(_ type: NSPasteboard.PasteboardType) throws {
    try withBridge { bridge, folder in
        copyImage(try fixture(), to: bridge.pasteboard, extraType: type)
        let count = bridge.pasteboard.changeCount
        #expect(try bridge.processClipboardIfChanged() == nil)
        #expect(bridge.pasteboard.changeCount == count)
        #expect(try FileManager.default.contentsOfDirectory(atPath: folder.path).isEmpty)
    }
}

@Test @MainActor
func existingClipboardAtStartupIsNotProcessed() throws {
    try withBridge { bridge, folder in
        copyImage(try fixture(), to: bridge.pasteboard)
        let fresh = ClipboardBridge(pasteboard: bridge.pasteboard, saveDirectory: folder)
        #expect(try fresh.processClipboardIfChanged() == nil)
    }
}

@Test @MainActor
func savedScreenshotUsesOriginalFileAndQuotesSpaces() throws {
    try withBridge { bridge, folder in
        let file = folder.appendingPathComponent("Screenshot at 10.30.png")
        try fixture().write(to: file)
        #expect(try bridge.processSavedScreenshot(file, expectedChangeCount: bridge.pasteboard.changeCount))
        #expect(bridge.lastFile == file)
        #expect(bridge.pasteboard.string(forType: .string) == "'\(file.path)'")
        #expect(try FileManager.default.contentsOfDirectory(atPath: folder.path).count == 1)
        try bridge.copyLastPathOnly()
        #expect(bridge.pasteboard.data(forType: .png) == nil)
        #expect(bridge.pasteboard.string(forType: .string) == "'\(file.path)'")
    }
}

@Test @MainActor
func delayedScreenshotDoesNotOverwriteNewerText() throws {
    try withBridge { bridge, folder in
        let file = folder.appendingPathComponent("screenshot.png")
        try fixture().write(to: file)
        let previous = bridge.pasteboard.changeCount
        bridge.pasteboard.clearContents()
        bridge.pasteboard.setString("newer copied text", forType: .string)
        #expect(try !bridge.processSavedScreenshot(file, expectedChangeCount: previous))
        #expect(bridge.pasteboard.string(forType: .string) == "newer copied text")
    }
}

@Test @MainActor
func invalidImageLeavesClipboardUntouched() throws {
    try withBridge { bridge, _ in
        let data = Data("not a PNG".utf8)
        copyImage(data, to: bridge.pasteboard)
        let count = bridge.pasteboard.changeCount
        #expect(throws: BridgeError.self) { try bridge.processClipboardIfChanged() }
        #expect(bridge.pasteboard.changeCount == count)
        #expect(bridge.pasteboard.data(forType: .png) == data)
    }
}

@Test @MainActor
func multipleClipboardItemsAreNotFlattened() throws {
    try withBridge { bridge, _ in
        let first = NSPasteboardItem(), second = NSPasteboardItem()
        first.setData(try fixture(), forType: .png)
        second.setData(try fixture(), forType: .png)
        bridge.pasteboard.clearContents()
        bridge.pasteboard.writeObjects([first, second])
        #expect(try bridge.processClipboardIfChanged() == nil)
        #expect(bridge.pasteboard.pasteboardItems?.count == 2)
    }
}

@Test
func terminalPathsQuoteMetacharactersSafely() {
    #expect(PathText.representation(of: URL(fileURLWithPath: "/tmp/a'b $(whoami).png"), quoteForTerminal: true)
        == "'/tmp/a'\\''b $(whoami).png'")
    #expect(PathText.representation(of: URL(fileURLWithPath: "/tmp/no-spaces.png"), quoteForTerminal: true) == "/tmp/no-spaces.png")
    #expect(PathText.representation(of: URL(fileURLWithPath: "/tmp/a b.png"), quoteForTerminal: false) == "/tmp/a b.png")
}

@Test
func screenshotMetadataWorksRegardlessOfFilename() throws {
    let file = FileManager.default.temporaryDirectory.appendingPathComponent("localized-\(UUID()).png")
    try Data().write(to: file)
    defer { try? FileManager.default.removeItem(at: file) }
    #expect(!ScreenshotFiles.isScreenshot(file))
    let metadata = try PropertyListSerialization.data(fromPropertyList: "true", format: .binary, options: 0)
    let result = metadata.withUnsafeBytes { bytes in
        setxattr(file.path, "com.apple.metadata:kMDItemIsScreenCapture", bytes.baseAddress, metadata.count, 0, 0)
    }
    #expect(result == 0)
    #expect(ScreenshotFiles.isScreenshot(file))
}

private func markScreenshot(_ file: URL) throws {
    let metadata = try PropertyListSerialization.data(fromPropertyList: "true", format: .binary, options: 0)
    let result = metadata.withUnsafeBytes { bytes in
        setxattr(file.path, "com.apple.metadata:kMDItemIsScreenCapture", bytes.baseAddress, metadata.count, 0, 0)
    }
    #expect(result == 0)
}

@Test @MainActor
func folderWatcherCopiesOnlyNewScreenshots() throws {
    try withBridge { bridge, folder in
        let old = folder.appendingPathComponent("old.png")
        try fixture().write(to: old)
        try markScreenshot(old)
        let watcher = ScreenshotWatcher(bridge: bridge)
        defer { watcher.pause() }
        watcher.watch(folder)
        let ordinary = folder.appendingPathComponent("ordinary.png")
        try fixture().write(to: ordinary)
        let screenshot = folder.appendingPathComponent("localized screenshot.png")
        try fixture().write(to: screenshot)
        try markScreenshot(screenshot)
        watcher.tick()
        #expect(bridge.lastFile?.resolvingSymlinksInPath() == screenshot.resolvingSymlinksInPath())
        let pastedFile = try #require(bridge.pasteboard.string(forType: .fileURL).flatMap(URL.init(string:)))
        #expect(pastedFile.resolvingSymlinksInPath() == screenshot.resolvingSymlinksInPath())
    }
}

@Test @MainActor
func delayedMetadataDoesNotReplaceNewCopy() throws {
    try withBridge { bridge, folder in
        let watcher = ScreenshotWatcher(bridge: bridge)
        defer { watcher.pause() }
        watcher.watch(folder)
        let screenshot = folder.appendingPathComponent("new.png")
        try fixture().write(to: screenshot)
        watcher.tick()
        bridge.pasteboard.clearContents()
        bridge.pasteboard.setString("copied during screenshot write", forType: .string)
        try markScreenshot(screenshot)
        watcher.tick()
        #expect(bridge.lastFile == nil)
        #expect(bridge.pasteboard.string(forType: .string) == "copied during screenshot write")
    }
}

@Test @MainActor
func materializedImagesAreOwnerOnly() throws {
    try withBridge { bridge, folder in
        copyImage(try fixture(), to: bridge.pasteboard)
        let file = try #require(try bridge.processClipboardIfChanged())
        let fileAttributes = try FileManager.default.attributesOfItem(atPath: file.path)
        let folderAttributes = try FileManager.default.attributesOfItem(atPath: folder.path)
        #expect((fileAttributes[.posixPermissions] as? NSNumber)?.intValue == 0o600)
        #expect((folderAttributes[.posixPermissions] as? NSNumber)?.intValue == 0o700)
    }
}

@Test @MainActor
func imageStoreRefusesOverwriteAndSymlinkDirectory() throws {
    try withBridge { _, folder in
        let file = folder.appendingPathComponent("existing.png")
        try Data("original".utf8).write(to: file)
        #expect(throws: POSIXError.self) { try PrivateImageStore.write(Data("replacement".utf8), to: file) }
        #expect(try String(contentsOf: file, encoding: .utf8) == "original")
        let link = folder.appendingPathComponent("link")
        try FileManager.default.createSymbolicLink(at: link, withDestinationURL: folder)
        #expect(throws: BridgeError.self) { try PrivateImageStore.prepareDirectory(link) }
    }
}

@Test @MainActor
func savedScreenshotSymlinkIsRejected() throws {
    try withBridge { bridge, folder in
        let image = folder.appendingPathComponent("original.png")
        try fixture().write(to: image)
        let link = folder.appendingPathComponent("link.png")
        try FileManager.default.createSymbolicLink(at: link, withDestinationURL: image)
        let count = bridge.pasteboard.changeCount
        #expect(throws: BridgeError.self) { try bridge.processSavedScreenshot(link, expectedChangeCount: count) }
        #expect(bridge.pasteboard.changeCount == count)
    }
}

@Test(arguments: [(0, 1), (-1, 1), (Int.max, Int.max), (10_000, 10_000)])
func invalidOrExcessiveDimensionsAreRejected(_ size: (Int, Int)) {
    #expect(throws: BridgeError.self) { try ImagePayload.validateDimensions(width: size.0, height: size.1) }
}

@Test
func normalScreenshotDimensionsAreAllowed() throws {
    try ImagePayload.validateDimensions(width: 6016, height: 3384)
}

@Test @MainActor
func newestSavedScreenshotWinsWhenFilesArriveTogether() throws {
    try withBridge { bridge, folder in
        let watcher = ScreenshotWatcher(bridge: bridge)
        defer { watcher.pause() }
        watcher.watch(folder)
        let first = folder.appendingPathComponent("first.png")
        let last = folder.appendingPathComponent("last.png")
        for (file, offset) in [(first, 1.0), (last, 2.0)] {
            try fixture().write(to: file)
            try markScreenshot(file)
            try FileManager.default.setAttributes([.creationDate: Date().addingTimeInterval(offset)], ofItemAtPath: file.path)
        }
        watcher.tick()
        #expect(bridge.lastFile?.resolvingSymlinksInPath() == last.resolvingSymlinksInPath())
    }
}
